commit module2 with trelloitems with api key and token
domrk98git/DevOps-Course-Starter pull request #5
Opened 2021-02-23 21:52 UTC by domrk98git

2021-03-04 12:13 UTC, hugh-emerson requested changes
Generally looks good but could you try the last task of the exercise - creating/using a class? See my comment on trelloitems.py line 42 for details.

See my other comments for some minor suggestions.

Please resubmit in Aptem once it is ready for re-review

2021-03-04 12:13 UTC, hugh-emerson commented on README.md
> +add .jason to above to lookup boardid, listid details
```suggestion
add .json to above to lookup boardid, listid details 
```

2021-03-04 12:13 UTC, hugh-emerson commented on todo_app/app.py
> +from todo_app.data import session_items,trelloitems
You shouldn't be importing session_items anymore. In fact you should delete the session_items.py file.

2021-03-04 12:13 UTC, hugh-emerson commented on todo_app/app.py
>  ##  if request.method == 'POST':
Delete commented out code.

2021-03-04 12:13 UTC, hugh-emerson commented on todo_app/data/trelloitems.py
> +    print(response.json())
You normally shouldn't keep print statements around

2021-03-04 12:13 UTC, hugh-emerson commented on todo_app/data/trelloitems.py
> +todo_id='6032b49b5e077170a897e558'
Even though these are not sensitive values, they are the kind of thing that will vary between environments:
- your test server shouldn't be saving cards to the same board as the production server
- developers will each have their own

So it's still nicer to load them via os.getenv

(And that will help a lot with writing tests in module 3 )

2021-03-04 12:13 UTC, hugh-emerson commented on todo_app/data/trelloitems.py
> +    return response.json()
The exercise asks you to try defining a `class` to represent each item.

You would then use it here, mapping from the trello data to a list of your objects, and returning that instead.

2021-03-04 12:13 UTC, hugh-emerson commented on todo_app/data/trelloitems.py
> +    url = f"https://api.trello.com/1/lists/{todo_id}/cards"
It would be nice to fetch completed items too. (You need to for module 3)

2021-03-04 12:13 UTC, hugh-emerson commented on todo_app/data/trelloitems.py
> +def UpdateToDone(card_id):
The python naming convention is snake_case for variable/function names, and only PascalCase for class names

2021-03-04 12:13 UTC, hugh-emerson commented on todo_app/app.py
> +@app.route('/UpdateToDone',methods=['POST', 'GET'])
You currently only send GET requests to this endpoint (because you're using an anchor element, `<a>`).

So adding POST here is unnecessary and misleading

2021-03-04 12:13 UTC, hugh-emerson commented on .vagrant/machines/default/virtualbox/action_provision
> +1.5:273e8fc1-152d-42b6-a9c7-5301d94f7df6
You've accidentally included the .vagrant folder from switching branch

2021-03-05 10:44 UTC, merged

2021-03-12 09:52 UTC, JackMead commented
Thanks for updating that, happy that this is now using a class to display those items.

I can see you've extracted almost all of the environment variables - it's worth noting that there's still one hardcoded list id in `create_item` which means only if configured with your Trello account would the program be able to create new items. It would also be nice to add the new keys for those environment variables into the `.env.template`, and into your README, so that those are up to date